version: "3.7"
services:
  aspen:
    build: ./
    command: run
    image: duke/duke:latest
    container_name: duke_${BRANCH_NAME}
    restart: always
    secrets:
      - webhooks.yml
secrets:
  webhooks.yml:
    file: webhooks.yml